cinema/urls.py
from django.urls import path
from . import views

app_name = 'cinema'

urlpatterns = [
    path('', views.cine, name='index'),
    path('news/', views.news, name='news'),
    path('films/', views.films, name='films'),
    path('reservations/', views.reservations, name='reservations'),
    # path(r'^films/(?P<pk>\d+)$', views.FilmsDetailView.as_view(), name='filmsDetail'),
    # path('films/<int:pk>', views.FilmsDetailView.as_view(), name='filmsDetail'),
    path('films/<int:idfilm>', views.filmsDetail, name='filmDetail'),
]

reservation/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings

from xml.etree.ElementInclude import include
from django.urls import path, re_path,  include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve 



urlpatterns = [
    path('admin/', admin.site.urls),
    path('cinema/', include('cinema.urls', namespace='cinema')),


    re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$',serve,{'document_root':settings.STATIC_ROOT}),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cinema/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

# Create your models here.

class Utilisateur(AbstractUser):

    def __str__(self):
        return self.username 

class Categorie(models.Model):
    libelle = models.CharField(max_length=200, null=False)
    created_at =models.DateTimeField(auto_now_add=True)
    updated_at =models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('-created_at',)
    
    def __str__(self):
        return f'{self.libelle} {self.id}' 




class Films(models.Model):
    titre = models.CharField(max_length=200, null=False) 
    description = models.CharField(max_length=200, null= False)
    version = models.CharField(max_length=200, null=False)
    prix = models.IntegerField(default=0) 
    image = models.ImageField(upload_to="Films/",null=False, blank=False)
    auteur = models.CharField(max_length=200, null = False)
    # horaire_dep_diff = models.DateTimeField()
    # horaire_fin_diff = models.DateTimeField()
    horaire_diff = models.DateTimeField()
    Categorie = models.ForeignKey(Categorie, on_delete = models.CASCADE) 
    created_at =models.DateTimeField(auto_now_add=True)
    updated_at =models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('-created_at',)
    
    def __str__(self):
        return f'{self.titre}' 


class Ticket(models.Model):
    numero = models.IntegerField(default=1)
    films = models.ForeignKey(Films, on_delete = models.CASCADE) 
    user = models.ForeignKey(Utilisateur, on_delete = models.CASCADE)
    created_at =models.DateTimeField(auto_now_add=True)
    updated_at =models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('-created_at',)
    
    def __str__(self):
        return f'{self.numero}'


class Place(models.Model):
    numPlace = models.IntegerField(default = 1)
    ticket = models.ForeignKey(Ticket, on_delete = models.CASCADE)
    created_at =models.DateTimeField(auto_now_add=True)
    updated_at =models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('-created_at',)
    
    def __str__(self):
        return f'{self.numPlace}'


class Salle(models.Model):
    nom = models.CharField(max_length=200, null = False)
    lieu = models.CharField(max_length=200, null = False)
    place = models.ForeignKey(Place, on_delete = models.CASCADE)
    created_at =models.DateTimeField(auto_now_add=True)
    updated_at =models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('-created_at',)
    
    def __str__(self):
        return f'{self.nom}'

cinema/views.py
from django.shortcuts import render
from unicodedata import name
from cinema.models import Categorie, Films, Ticket, Utilisateur, Salle, Place
from django.views import generic

# Create your views here.

def cine(request, *arg, **kwarg):
    films = Films.objects.all()
    categorie = Categorie .objects .all()
    context = {
        'films' : films
    }

    # context['films'] = films
    context['categorie'] = categorie

    return render(request, 'cinema/index.html', context)


def films(request, *arg, **kwarg):
    films = Films.objects.all()
    categorie = Categorie .objects .all()
    context = {
        'films' : films
    }


    # context['films'] = films
    context['categorie'] = categorie

    return render(request, 'cinema/films_list.html', context)    


def reservations(request, *arg, **kwarg):
    context = {}
    return render(request, 'cinema/reservations.html', context)      

def news(request, *arg, **kwarg):
    
    films = Films.objects.all()
    categorie = Categorie .objects .all()
    context = {
        'films' : films
    }

    # context['films'] = films
    context['categorie'] = categorie

    return render(request, 'cinema/new.html', context)



def filmsDetail(request, idfilm):
    film = None
    try:
        film = Films.objects.get(pk=idfilm) 
       
    except Films.DoesNotExist:
        raise  http404('Films does not exist') 
    
    return render(request, 'cinema/detail_film.html', context={'film': film})

class FilmsDetailView(generic.DetailView):
     model = Films
    # context_object_name = 'films'
    # queryset = Films.objects.all()
    # films = Films.objects.get(pk=primary_key) 
    # queryset = Films.objects.filter(titre__icontains='loup'[:2])
    # template_name = 'fimls/detail_list.html'

class FilmsListView(generic.ListView):

    model = Films
    context_object_name = 'films'
    queryset = Films.objects.all()
    # queryset = Films.objects.filter(titre__icontains='loup'[:2])
    template_name = 'fimls/films_list.html'

cinema/templates/cinema/detail_film.html
{% extends 'reservation/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'cinema/css/detail.css' %}">
{% endblock %}

{% block title %}
<title>Réservation | {{film.titre}} </title>
{% endblock %}
{% block content %}

<div class="imgDetail" style="margin-top: 40px;">
    <div class="arriere"></div>

    <div class="elment1">
        <div class="imag1">
            <img src="{{ film.image.url }}" alt="{{film.titre}}">
            <div class="texts">
                <div class="titre">
                    <h4>{{film.titre}}</h4>
                </div>
                <div class="prix">
                    <p>{{film.prix}}£</p>
                </div>

            </div>
            <div class="version">
                <p>{{film.version}}</p>
            </div>
        </div>


    </div>
    <div class="informations">
        <div class="description">
            <p><span>Horaire de diffusion: </span> {{ film.horaire_diff.date }} </p>
            <p><span>Salle de diffusion : </span>numerique</p>
            <p> <span>lundi/ mercredi/ samedi/: </span> {{ film.horaire_diff.time }} </p>
            <p> <span>mardi/ jeudi/ dimanche/: </span> {{ film.horaire_diff.time }} </p>
        </div>
        <div class="reserver">
            <button onclick="boite()">Reserver</button>
        </div>
        </dialog>
        <div id="boite">
            <div>
                <h4>Choisir le jour</h4>
                <select name="jour" id="selection">
                    <option value="lundi">Lundi</option>
                    <option value="mardi">Mardi</option>
                    <option value="mercredi">Mercredi</option>
                    <option value="jeudi">Jeudi</option>
                    <option value="vendredi">Vendredi</option>
                    <option value="samedi">Samedi</option>
                    <option value="dimanche">Dimanche</option>
                </select>
                <h4>Choisir le nombre de place</h4>
                <input type="number" name="" id="nombre">
                <button onclick="soumettre(event)">Valider le reservation</button>
            </div>
        </div>

        </dialog>

    </div>
</div>

</div>

<div>

    <div class="description">
        <h3>Description</h3>
        <p>c'est l'histoire de gulain et sa femme verone qui quittent leur contré pour un
            autre pays lors des vacances d'été.c'est l'histoire de gulain et sa femme verone qui quittent leur contré
            pour un
            autre pays lors des vacances d'été.
        </p>
    </div>

    <div class="infos">
        <h3>Information sur le films</h3>
        <p><span>Réalisé par :</span> kyle Marvin</p>
        <p><span>Genre :</span>comédie</p>
        <p><span>qualité : </span>numerique</p>

    </div>

    <div class="films">
      <H1>Films similaire</H1>
        {% for films in films %}
        <div class="elment1">
    
            <div class="imag1">
    
                <img src="{{ films.image.url }}" alt="">
                <div class="texts">
                    <div class="titre">
                        <h4>{{ films.titre }}</h4>
                    </div>
                    <div class="prix">
                        <p>{{ films.prix }}£</p>
                    </div>
    
                </div>
            </div>
    
            <div class="panier">
                <button>+1panier</button>
            </div>
    
            <div class="detail">
                <a href="{{ detail }}">Voir la fiche>></a>
            </div>
        </div>
        {% endfor %}
    </div>

</div>

</div>
<script>
    function boite(event) {
        reservation = document.getElementById("boite");
        reservation.style.visibility = reservation.style.visibility == "visible" ? "hidden" : "visible"

    }

    function soumettre(event) {
        let selection = document.querySelector("#selection")
        let nombre = document.querySelector("#nombre")
        if (nombre.value == "" || nombre.value <= 0) {
            alert("entrer un nombre positif")
        }

        reservation = document.getElementById("boite");
        reservation.style.visibility = reservation.style.visibility == "visible" ? "hidden" : "visible"
    }
</script>
{% endblock %}

cinema/templates/cinema/films_list.html
{% extends 'reservation/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'cinema/css/index.css' %}">
{% endblock %}

{% block title %}
<title>Réservation | Films</title>
{% endblock %}

{% block content %}

<div class="recherche">
    <input type="search" name="" id="searchs" placeholder="recherchez vous films">
    <img src="{% static 'cinema/images/recherches.jpg' %}" alt="">
</div>
<div class="card">
    <div class="textes">
        <h2>
            Bienvenue sur <span>TicketBooking</span>
            votre site de reservation de billet de cinéma

        </h2>

        <h4>
            Choisissez votre films et reserver au plus vite
        </h4>
    </div>
    <div class="image1">
        <img src="{% static 'cinema/images/nav2.jpg' %}" alt="">
    </div>
</div>

<div class="categorie">
    {% for categorie in categorie %}
    <a href="">{{ categorie.libelle }}</a>
    {% endfor %}

</div>

<div class="films">
    {% for film in films %}
    <div class="elment1">

        <div class="imag1">

            <img src="{{ film.image.url }}" alt="">
            <div class="texts">
                <div class="titre">
                    <h4>{{ film.titre }}</h4>
                </div>
                <div class="prix">
                    <p>{{ film.prix }}FCFA </p>

                </div>

            </div>
        </div>

        <div class="panier">
            <button>+1panier</button>
        </div>

        <div class="detail">
            <a href="{% url 'cinema:filmDetail' film.id %}">Voir la fiche>></a>
        </div>
    </div>
    {% endfor %}
</div>
</section>
{% endblock %}

cinema/templates/cinema/index.html
{% extends 'reservation/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'cinema/css/index.css' %}">
{% endblock %}

{% block title %}
    <title>Réservation | Accueil</title>
{% endblock %}
{% block content %}
<div class="recherche">
    <input type="search" name="" id="searchs" placeholder="recherchez vous films">
    <img src="{% static 'cinema/images/recherches.jpg' %}" alt="">
</div>

<div class="card">

    <div class="textes">
        <h2>
            Bienvenue sur <span>TicketBooking</span>
            votre site de reservation de billet de cinéma

        </h2>
        <h4>
            Obtenez votre ticket de reservation en quelques cliques
        </h4>
    </div>
    <div class="image1">
        <img src="{% static 'cinema/images/nav.jpg' %}" alt="">
    </div>
</div>

<div class="categorie">
    {% for categorie in categorie %}
    <a href="">{{ categorie.libelle }}</a>
    {% endfor %}

</div>
<div class="films">
    {% for films in films %}
    <div class="elment1">

        <div class="imag1">

            <img src="{{ films.image.url }}" alt="">
            <div class="texts">
                <div class="titre">
                    <h4>{{ films.titre }}</h4>
                </div>
                <div class="prix">
                    <p>{{ films.prix }}£</p>
                </div>

            </div>
        </div>

        <div class="panier">
            <button>+1panier</button>
        </div>

        <div class="detail">
            <a href="{{ detail }}">Voir la fiche>></a>
        </div>
    </div>
    {% endfor %}
</div>
<div class="voir">
    <a href="product.html">voir plus...</a>
</div>

</section>

{% endblock %}

cinema/templates/cinema/new.html
{% extends 'reservation/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'cinema/css/new.css' %}">
{% endblock %}

{% block title %}
<title>Réservation | News</title>
{% endblock %}

{% block content %}
    <section class="section1">
        
        <div class="card">

            <img src="{% static 'cinema/images/nav2.jpg' %}" alt="">
            <div class="textes" >
                <h2>
                    Bienvenue sur <span>TicketBooking</span> 
                    votre site de reservation de billet de cinéma

                </h2>
            
                <h4>
                    ici vous trouverez des films inédit (jamais diffusés)
                    et surtout aux prix imbatables
                </h4>
                
            </div>

            <div class="recherche">
                <input type="search" name="" id="searchs" placeholder="recherchez vous films">
                <img src="{% static 'cinema/images/recherches.jpg' %}" alt="">
            </div>
        </div>

        <div class="categorie">
        {% for categorie in categorie %}
        <a href="">{{ categorie.libelle }}</a>
        {% endfor %}
        
    </div>
    <div class="films">
        {% for films in films %}
        <div class="elment1">
            
            <div class="imag1">
                
                <img src="{{ films.image.url }}" alt="" >
                <div class="texts">
                    <div class="titre">
                        <h4>{{ films.titre }}</h4>
                    </div>
                    <div class="prix">
                        <p>{{ films.prix }}£</p>
                    </div>
                    
                </div>
            </div>
                    
            <div class="panier">
                <button>+1panier</button>
            </div>

            <div class="detail">
                <a href="{{ detail }}" >Voir la fiche>></a>
            </div>
        </div>
        {% endfor %}
    </div>


    </section>
{% endblock %}

cinema/templates/cinema/reservations.html
{% extends 'reservation/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'cinema/css/index.css' %}">
{% endblock %}

{% block title %}
    <title>Réservation | Reservations</title>
{% endblock %}
{% block content %}


{% endblock %}

templates/reservation/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=!, initial-scale=1.0">
    {% block css %}
    {% endblock %}
    {% block title %}
    {% endblock %}
</head>
<body>
    <section class="section1">
        <div class="alle">
            <div>
                <h1>Ticket<span>Booking</span></h1>
            </div>
            <div class="liens">
                <a href="{% url 'cinema:index' %}">Home</a>
                <a href="{% url 'cinema:films' %}">Films</a>
                <a href="{% url 'cinema:films' %}">Tickets</a>
                <a href="{% url 'cinema:news' %}">News</a>
                <a href="{% url 'cinema:reservations' %}">Reservations</a>
            </div>
        </div>

        {% block content %}
        {% endblock %}

        <div style="margin-top: 30px; color: white; font-size: 22px; padding: 30px;">
            <p style="text-align: center;">Votre site de reservation de billet de cinema en ligne</p>
        </div>
</body>

</html>